all:
  hosts:
    App_Machine:
      ansible_host: 34.239.120.221 
      ansible_user: ubuntu     
      ansible_ssh_private_key_file: "/home/ubuntu/.shh/my-key.pem"
    app_vm:
      ansible_host: 20.123.45.67   # Public IP of the Azure VM
      ansible_user: azureuser      # SSH user for Azure VM
      ansible_ssh_private_key_file: "/home/ubuntu/.shh/id_rsa.pub"  # Path to your Azure private key