all:
  hosts:
    App_Machine:
      ansible_host: 54.197.78.130 
      ansible_user: ubuntu     
      ansible_ssh_private_key_file: "/home/ubuntu/.ssh/my-key.pem"
    app_vm:
      ansible_host: 20.84.55.82   # Public IP of the Azure VM
      ansible_user: azureuser      # SSH user for Azure VM
      ansible_ssh_private_key_file: "/home/ubuntu/.ssh/app-vm_key.pem"  # Path to your Azure private key